### ISSUE TITLE
[Enhancement] Create a KCL Flux Controller

### ISSUE THREAD

**Issue by steeling** [kcl-lang/flux-kcl-controller#9]
## Enhancement
This is probably the wrong place for this, but I wanted to add a request for creating a flux controller. Flux currently supports helm (beta, with a lot of missing features in drift detection), and kustomize (but this can also just be native k8s yaml files).

A flux controller would allow us to create and manage our kcl manifests directly from our repo, without any additional tooling or pre-rendering.

This could be done be either creating a controller akin to the kustomize controller, or a new [source controller](https://fluxcd.io/flux/components/source/). This source controller would be chained to another source controller, such that it:

1. Reads from the initial source controller. This would be an existing source controller like bucket, or git repo.
2. Renders the yaml manifests, then serves the render yaml to the kustomize controller.

**Comment by Peefy** [comment]
The initial implementation version is here: https://github.com/kcl-lang/flux-kcl-controller and I'll transfer this issue to the repo.
